#!/bin/bash


echo "alias creados shortcut

tinyurl.com/zeroinst
https://raw.githubusercontent.com/4rji/4rji/main/binarios/zeroinst

tinyurl.com/ccdcmsp
https://raw.githubusercontent.com/4rji/ccdc/main/ccdc.sh

tinyurl.com/torrelay
https://raw.githubusercontent.com/4rji/4rji/main/binarios/torrelay

tinyurl.com/herrabin
https://raw.githubusercontent.com/4rji/4rji/main/binarios/herrabin "
