#!/bin/bash

# Definir las opciones y sus URLs
declare -A options
options["zerotier"]="https://raw.githubusercontent.com/4rji/4rji/main/binarios/zeroinst"
options["CCDC"]="https://raw.githubusercontent.com/4rji/ccdc/main/ccdc.sh"
options["torrelay"]="https://raw.githubusercontent.com/4rji/4rji/main/binarios/torrelay"
options["herrabin"]="https://raw.githubusercontent.com/4rji/4rji/main/binarios/herrabin"

# Mostrar las opciones en un menú
echo "Cual script quieres descargar y ejecutar:"
echo ""
select opt in "${!options[@]}" "Salir"; do
    case $opt in
        "Salir")
            echo "Saliendo..."
            exit 0
            ;;
        *)
            if [[ -n "${options[$opt]}" ]]; then
                URL_elegida="${options[$opt]}"
                echo "Ejecutando wget -O - $URL_elegida | bash"
                wget -O - "$URL_elegida" | bash
                break
            else
                echo "Opción inválida. Intenta de nuevo."
            fi
            ;;
    esac
done