#!/bin/bash

# Definir el archivo de hosts de Ansible
archivo_hosts="$HOME/.ssh/ansible_hosts"

# Función para agregar un host al archivo de inventario
agregar_host() {
    echo -n "Ingresa el nombre del host o dirección IP: "
    read host

    echo -n "Ingresa el puerto (por defecto es 22): "
    read puerto
    if [ -z "$puerto" ]; then
      puerto=22 # Puerto por defecto de SSH
    fi

    echo -n "Ingresa el nombre de usuario: "
    read usuario

    # Preguntar por el uso de llave privada
    echo -n "¿Quieres especificar una llave privada? [s/n]: "
    read usar_llave
    if [ "$usar_llave" = "s" ]; then
      echo "Llaves privadas disponibles:"
      select ruta_llave in ~/.ssh/*; do
        if [ -n "$ruta_llave" ]; then
          echo "Has seleccionado $ruta_llave"
          llave="ansible_ssh_private_key_file=$ruta_llave"
          break
        else
          echo "Por favor, elige un número de la lista."
        fi
      done
    else
      llave=""
    fi

    # Agregar o crear el archivo de hosts con la configuración
    echo "$host ansible_port=$puerto ansible_user=$usuario $llave" >> $archivo_hosts

    echo "Host $host agregado al archivo de inventario '$archivo_hosts'."
}

# Preguntar si deseas agregar un host [S/n]
echo -n "¿Deseas agregar un host? [S/n]: "
echo " n para modificar puerto SSH a los host"
read respuesta
if [ "$respuesta" = "n" ] || [ "$respuesta" = "N" ]; then
    modificar_puerto="s"  # Si no se agrega un host, se asume que se desea modificar el puerto SSH.
else
    agregar_host
fi

echo ""

if [[ "$modificar_puerto" == "s" ]]; then
    # Preguntar si deseas modificar el puerto SSH
    read -p "¿Deseas modificar el puerto SSH en todos los hosts? [s/n]: " modify_port

    if [[ $modify_port == "s" ]]; then
        # Pedir el nuevo puerto SSH
        read -p "Ingresa el nuevo puerto SSH: " new_ssh_port

        # Actualizar el archivo de hosts de Ansible con el nuevo puerto SSH
        sed -i "s/ansible_port=[0-9]*/ansible_port=$new_ssh_port/g" $archivo_hosts

        echo "El puerto SSH ha sido modificado en todos los hosts a $new_ssh_port."
    else
        echo "No se ha modificado el puerto SSH."
    fi
fi
