#!/bin/bash
echo ""
# Definir el archivo de hosts de Ansible
archivo_hosts="$HOME/.ssh/ansible_hosts"

# Función para agregar un host al archivo de inventario
agregar_host() {
    echo -n "Ingresa el nombre del host o dirección IP: "
    read host

    echo -n "Ingresa el puerto (por defecto es 22): "
    read puerto
    if [ -z "$puerto" ]; then
        puerto=22 # Puerto por defecto de SSH
    fi
	
    echo -n "Ingresa el nombre de usuario: "
    read usuario

    # Preguntar por el uso de llave privada
    echo -n "¿Quieres especificar una llave privada? [s/n]: "
    read usar_llave
    if [ "$usar_llave" = "s" ]; then
        echo "Llaves privadas disponibles:"
        select ruta_llave in ~/.ssh/*; do
            if [ -n "$ruta_llave" ]; then
                echo "Has seleccionado $ruta_llave"
                llave="ansible_ssh_private_key_file=$ruta_llave"
                break
            else
                echo "Por favor, elige un número de la lista."
            fi
        done
    else
        llave=""
    fi

    # Agregar o crear el archivo de hosts con la configuración
    echo "$host ansible_port=$puerto ansible_user=$usuario $llave" >> $archivo_hosts

    echo "Host $host agregado al archivo de inventario '$archivo_hosts'."

echo ""
echo ""
    # Preguntar si desea agregar otro host
    echo -n "¿Deseas agregar otro host? [s/n]: "
    read respuesta
    if [ "$respuesta" = "s" ] || [ "$respuesta" = "S" ]; then
        agregar_host # Llamar recursivamente a la función para agregar otro host
    else
        return 0 # Terminar la función si el usuario no desea agregar más hosts
    fi
}

modificar_puerto_ssh() {
    # Preguntar si deseas modificar el puerto SSH
	echo ""
    echo -n "¿Deseas modificar el puerto SSH en todos los hosts? [s/n]: "
    read modify_port

    if [[ $modify_port == "s" ]]; then
        # Pedir el nuevo puerto SSH
        echo -n "Ingresa el nuevo puerto SSH: "
        read new_ssh_port

        # Actualizar el archivo de hosts de Ansible con el nuevo puerto SSH
        sed -i "s/ansible_port=[0-9]*/ansible_port=$new_ssh_port/g" $archivo_hosts

        echo "El puerto SSH ha sido modificado en todos los hosts a $new_ssh_port."
    else
        echo "No se ha modificado el puerto SSH."
    fi
}

# Preguntar si deseas agregar un host al inicio
echo -n "¿Deseas agregar un host? [S/n]: "
read respuesta
if [ "$respuesta" != "n" ] && [ "$respuesta" != "N" ]; then
    agregar_host
fi

modificar_puerto_ssh
