#!/bin/zsh

# Clone the Artillery repository
#git clone https://github.com/BinaryDefense/artillery.git

#Download from my repo
wget https://github.com/4rji/4rji/blob/main/artillery.zip

unzip artillery.zip
# Change to the artillery directory
cd artillery/

# Run the setup script
sudo ./setup.py


echo "modificar el archivo"
echo "/var/artillery/config"