#!/bin/bash

# Define las funciones
functions_to_add='
# Functions
function mkt(){
    mkdir "$1" && cd "$1" && mkdir nmap && mkdir content && mkdir exploits && mkdir scripts && echo "nuevo directorio" && pwd && ls
}

function mktem() {
    new_dir=$(mktemp -d)
    echo "Directorio creado en: $new_dir"
    cd "$new_dir" || return
    echo "Cambiado al directorio: $PWD"
}


function extractPorts(){
    ports="$(cat $1 | grep -oP '\d{1,5}/open' | awk '{print $1}' FS='/' | xargs | tr ' ' ',')"
    ip_address="$(cat $1 | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u | head -n 1)"
    echo -e "\n[*] Extracting information...\n" > extractPorts.tmp
    echo -e "\t[*] IP Address: $ip_address"  >> extractPorts.tmp
    echo -e "\t[*] Open ports: $ports\n"  >> extractPorts.tmp
    echo $ports | tr -d '\n' | xclip -sel clip
    echo -e "[*] Ports copied to clipboard\n"  >> extractPorts.tmp
    cat extractPorts.tmp; rm extractPorts.tmp
}

# fzf improvement
function fzf-lovely(){

    if [ "$1" = "h" ]; then
        fzf -m --reverse --preview-window down:20 --preview '[[ $(file --mime {}) =~ binary ]] &&
                    echo {} is a binary file ||
                     (bat --style=numbers --color=always {} ||
                      highlight -O ansi -l {} ||
                      coderay {} ||
                      rougify {} ||
                      cat {}) 2> /dev/null | head -500'

    else
            fzf -m --preview '[[ $(file --mime {}) =~ binary ]] &&
                             echo {} is a binary file ||
                             (bat --style=numbers --color=always {} ||
                              highlight -O ansi -l {} ||
                             coderay {} ||
                              rougify {} ||
                              cat {}) 2> /dev/null | head -500'
    fi
}






function rmk(){
    scrub -p dod $1
    shred -zun 10 -v $1
}'

# Rutas a los archivos .bashrc y .zshrc
bashrc="$HOME/.bashrc"
zshrc="$HOME/.zshrc"

# Agregar las funciones al final de .bashrc y .zshrc
echo "$functions_to_add" >> "$bashrc"
echo "$functions_to_add" >> "$zshrc"

echo "Funciones agregadas a .bashrc y .zshrc"

