#!/bin/bash

# Función para detectar la distribución de Linux
detectar_distro() {
    if [[ -f /etc/debian_version ]]; then
        DISTRO="Debian"
    elif [[ -f /etc/redhat-release ]]; then
        DISTRO="RedHat"
    elif [[ -f /etc/arch-release ]]; then
        DISTRO="Arch"
    else
        DISTRO="Unknown"
    fi
}

# Función para buscar un paquete
buscar_paquete() {
    echo ""
    read -p "Introduce el nombre parcial o completo del paquete que quieres buscar: " paquete
    echo ""
    echo "Buscando paquetes que coincidan con '$paquete'..."
    echo ""
    echo ""    
    case $DISTRO in
        Debian)
            dpkg -l | grep "$paquete" 2>/dev/null
            ;;
        RedHat)
            rpm -qa | grep "$paquete" 2>/dev/null
            ;;
        Arch)
            pacman -Qs "$paquete" 2>/dev/null
            ;;
        *)
            echo "Distribución no soportada o no detectada."
            ;;
    esac
}


# Función para buscar servicios relacionados
buscar_servicios() {
    echo ""
    echo ""
    echo ""
        echo "   **********************************************"
    echo ""
    echo ""
        echo "Buscando servicios que coincidan con '$paquete'..."
    sleep 1
    echo ""
    systemctl list-units --type service --all | grep "$paquete" 2>/dev/null
    echo ""
}

# Principal
detectar_distro
buscar_paquete
buscar_servicios

