#!/bin/bash

echo "Elige una opción para tu búsqueda:"
echo "1. Buscar por nombre"
echo "2. Buscar por extensión"
echo "3. Buscar archivo específico"
echo "4. Buscar por tamaño"
echo "5. Buscar directorio"
read opcion

echo "Directorio en el que buscar:"
read directorio

echo "Ingresa tu búsqueda:"
read busqueda

echo "Max depth (ingresa un número o presiona Enter para sin límite):"
read maxdepth

# Construir el comando find base
comando="find $directorio"

# Agregar maxdepth si es necesario
if [[ ! -z "$maxdepth" ]]; then
    comando="$comando -maxdepth $maxdepth"
fi

# Agregar opciones basadas en la elección del usuario
case $opcion in
    1)
        # Buscar por nombre, insensible a mayúsculas y minúsculas
        comando="$comando -iname \"*${busqueda}*\""
        ;;
    2)
        # Buscar por extensión
        comando="$comando -type f -name \"*.${busqueda}\""
        ;;
    3)
        # Buscar archivo específico
        comando="$comando -name \"${busqueda}\""
        ;;
    4)
        # Buscar por tamaño
        comando="$comando -size ${busqueda}"
        ;;
    5)
        # Buscar directorio
        comando="$comando -type d -iname \"*${busqueda}*\""
        ;;
    *)
        echo "Opción no válida"
        exit 1
        ;;
esac

echo "Ejecutando comando:"
echo ""
echo "$comando"
echo ""
echo "comando copiado al portapapeles"
sleep 1
echo "$comando" | xclip -selection clipboard
echo ""
eval $comando
