#!/bin/zsh


#mover readme con lista en dos para 4rjic
./partir_readme
cp -f README.md dosl unol ~/4rji/binarios/

sudo rm /usr/bin/dosl
sudo rm /usr/bin/unol

#fix scripts
#sudo mv -f ~/4rji/binarios/* /usr/bin/
sudo cp -f ~/4rji/binarios/* /usr/bin/
cd ..

cd ~
adios 4rji
echo "binarios actualizados y 4rji borrado"

