#!/bin/bash

# Función para verificar si un paquete está instalado

paquetes=("curl" "git" "kitty" "nano" "sudo" "zsh" "xclip")

paquete_instalado() {  
    dpkg -l "$1" | grep -q '^ii'  
}

for paquete in "${paquetes[@]}"; do
    if ! paquete_instalado "$paquete"; then  
        sudo apt-get install -y "$paquete"  
    fi  
done



#funcion mktemp

function mktem() {
    new_dir=$(mktemp -d)
    echo "Directorio creado en: $new_dir"
    cd "$new_dir" || return
    echo "Cambiado al directorio: $PWD"
}




# Aquí puedes llamar a la función mktem
mktem

git clone https://github.com/4rji/4rji.git
cd 4rji/

./alias.sh

sudo cp -f binarios/* /usr/bin/

echo "binarios actualizados"
cd
echo ""
echo "Si hay: Error opening terminal: xterm-kitty, ejecutar:"
echo "export TERM=xterm"