#!/bin/zsh
echo ""
echo "***************IP local ********"
hostname -I | awk '{print $1}'
echo ""
echo "IP publica localmente encontrada"
dig +short myip.opendns.com @resolver1.opendns.com
echo ""


# Ejecutar hostnamectl y guardar la salida en un archivo temporal
tmpfile=$(mktemp)
hostnamectl > "$tmpfile"

# Eliminar las líneas no deseadas del archivo temporal
sed -i '/Machine ID:/d; /Boot ID:/d; /Firmware Version:/d; /Firmware Date:/d; /Firmware Age:/d' "$tmpfile"

# Mostrar el contenido del archivo modificado
bat -l rb "$tmpfile"
# Eliminar el archivo temporal
rm "$tmpfile"


echo ""

# Función para comprobar la conexión a Internet
check_internet_connection() {
    echo ""
    curl ifconfig.me
    local host="google.com"  # Cambia "google.com" por el host que desees

    ping -c 1 "$host" > /dev/null 2>&1

    if [[ $? -eq 0 ]]; then
        echo " <== tu IP.  La conexión a Internet está ACTIVA."
    else
        echo "No se puede acceder a Internet."
    fi
}

# Preguntar si se desea ejecutar el script
echo "¿Deseas verificar la conexión? (s para sí, enter para continuar)"
read response

if [[ "$response" == "s" ]]; then
    check_internet_connection
    # Guardar la salida de ipinfo.io en un archivo temporal
    tmpfile=$(mktemp)
    curl -s ipinfo.io | jq 'del(.loc, .org, .readme)' > "$tmpfile"

    # Mostrar el contenido del archivo temporal con bat
    bat -l rb "$tmpfile"
    # Eliminar el archivo temporal
    #rm "$tmpfile"
fi
