#!/bin/bash


# Lista de paquetes a instalar

paquetes=("lsof" "net-tools" "nmap")


# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {  
    dpkg -l "$1" | grep -q '^ii'  
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done












# Función para preguntar y ejecutar lsof
preguntar_y_ejecutar_lsof() {
    read -p "¿Ejecutar lsof? [Enter/n]: " respuesta
    if [[ $respuesta != "n" ]]; then
        sudo lsof -i -P -n
    fi
}

# Función para preguntar y ejecutar netstat
preguntar_y_ejecutar_netstat() {
    read -p "¿Ejecutar netstat? [Enter/n]: " respuesta
    if [[ $respuesta != "n" ]]; then
        netstat -tulpn
    fi
}

# Función para preguntar y ejecutar nmap en localhost
preguntar_y_ejecutar_nmap() {
    read -p "¿Ejecutar nmap localhost? [Enter/n]: " respuesta
    if [[ $respuesta != "n" ]]; then
        sudo nmap -T4 -p- --min-rate 1000 localhost
    fi
}

# Función para preguntar y ejecutar ps
preguntar_y_ejecutar_ps() {
    read -p "¿Ejecutar procesos? [Enter/n]: " respuesta
    if [[ $respuesta != "n" ]]; then
        ps -eo user,comm,pid
    fi
}

# Llamadas a las funciones
preguntar_y_ejecutar_lsof
preguntar_y_ejecutar_netstat
preguntar_y_ejecutar_nmap
preguntar_y_ejecutar_ps
