#!/bin/zsh

mostrar_procesos() {
    echo "Usuarios, Procesos y PIDs:"
    echo "----------------------------"

    # Obtener la lista de usuarios, procesos y PIDs
    ps_output=$(ps -eo user,comm,pid)
    lines=("${(@f)ps_output}")

    # Imprimir el encabezado
    printf "%-15s %-20s %-10s\n" "Usuario" "Proceso" "PID"
    echo "----------------------------"

    # Imprimir la lista de usuarios, procesos y PIDs en un formato más legible
    for line in "${lines[@]:2}"; do
        user=$(echo $line | awk '{print $1}')
        process=$(echo $line | awk '{print $2}')
        pid=$(echo $line | awk '{print $3}')
        printf "%-15s %-20s %-10s\n" "$user" "$process" "$pid"
    done

}

mostrar_procesos | sort



echo ""

echo " procesos | grep -v root" | sort | xclip -selection clipboard 

echo ""

  echo "Fin del script."
    echo ""
    echo "Ejecuta este comando para que no muestre los procesos de root:"
    echo "procesos | grep -v root | sort "
    echo ""
    echo "Tambien ese comando ya fue copiado al portapapeles"
    echo ""
    echo "Puedes usar:\nprocesos > procesos\n"
    echo "Esto para crear un archivo y buscar algun proceso en especifico"
    echo ""
    echo "ejemplos:\ncat procesos | sort | uniq | grep -v palabra1"
    echo "awk '{print $1 "\t" $2}' procesos | uniq | sort | grep -v root\n"
    echo "grep -i para incluir, grep -v para excluir root por ejemplo"


