#!/bin/bash

# Función para verificar si un paquete está instalado

paquetes=("rkhunter")

paquete_instalado() {  
dpkg -l "$1" | grep -q '^ii'  
}

for paquete in "${paquetes[@]}"; do if ! paquete_instalado "$paquete"; then  
sudo apt-get install -y "$paquete"  
fi  
done




echo "modificar los archivos"
echo "sudo nano /etc/rkhunter.conf"
echo "sudo nano /etc/default/rkhunter"
read -p "Quieres modificar los archivos? s/enter: " modificar



if [[ $modificar == "s" ]]; then
    sudo rkhunconf
    sudo rkhuncron
    echo "Archivos modificados con scripts"
    sleep 1
fi

# Pregunta al usuario si quiere actualizar la base de datos
read -p "Quieres actualizar la base de datos? s/enter: " actualizar

if [[ $actualizar == "s" ]]; then
    sudo rkhunter --update
fi


sleep 1
#listado de binarios abajo se ejecuta
#sudo rkhunter --propupd

# Preguntar al usuario si quiere ejecutar el escaneo
echo "¿Quieres ejecutar el escaneo ahora? (s/n): "
read respuesta

if [[ $respuesta = "s" ]]; then
    # Si el usuario responde 's', ejecutar rkhunter
    echo "Ejecutando rkhunter..."
    sudo rkhunter --propupd
    sudo rkhunter --check -sk
else
    # Si el usuario presiona enter o cualquier otra tecla, mostrar cómo ejecutarlo más tarde
    echo "Para escanear ejecute: sudo rkhunter --check -sk"
fi


echo ""
echo "comandos utiles"
echo "sudo rkhunter --versioncheck"
echo ""
echo "Para correr el scaner de nuevo"
echo "sudo rkhunter --check -sk"
