#!/bin/zsh

# Verifica el estado del servicio SSH
if systemctl is-active sshd &> /dev/null; then
  echo "El servicio SSH está          **^^   ACTIVO   ^^**."
  read "desactivar_ssh?¿Desea desactivar el servicio SSH? (s para si/Enter para continuar)"
  if [[ "$desactivar_ssh" == "s" ]]; then
    sudo systemctl stop sshd
    echo "El servicio SSH ha sido         ***  DESACTIVADO  *** ."
  else
    echo "No se ha desactivado el servicio SSH."
  fi
else
  echo "El servicio SSH está              ***  INACTIVO  ***."
  read "activar_ssh?¿Desea activar el servicio SSH? (s para si/Enter para continuar)"
  if [[ "$activar_ssh" == "s" ]]; then
    sudo systemctl start sshd
	echo
	interfaces=$(ip addr | awk '/^[0-9]+:/ {gsub(/:/,"",$2); iface=$2} /^    inet / {print iface, $2}')

# Mostrar las interfaces y sus direcciones IP
	echo "Interfaces de red y sus direcciones IP:"
	echo "$interfaces"

    ip_address=$(ip addr show wlp0s20f3 | awk '/inet / {print $2}' | cut -d/ -f1)

# Mostrar la dirección IP de wlp0s20f3
	echo ""
	echo "Dirección IP de wlp0s20f3: $ip_address"
	echo -n "user: "
	whoami
	echo ""
    echo "El servicio SSH ha sido         **^^  ACTIVADO  ^^**."

  else
    echo "No se ha activado el servicio SSH."
  fi
fi

