#!/bin/bash

# Obtener la lista de interfaces de red y sus direcciones IP
echo
interfaces=$(ip addr | awk '/^[0-9]+:/ {gsub(/:/,"",$2); iface=$2} /^    inet / {print iface, $2}')

# Mostrar las interfaces y sus direcciones IP
echo "Interfaces de red y sus direcciones IP:"
echo
echo "$interfaces"

# Agregar un renglón de separación
echo ""

# Obtener la dirección IP de la interfaz wlp0s20f3
ip_address=$(ip addr show wlp0s20f3 | awk '/inet / {print $2}' | cut -d/ -f1)

# Copiar la dirección IP de wlp0s20f3 al portapapeles
echo -n "$ip_address" | xclip -selection clipboard

echo ""
echo "Dirección IP de wlp0s20f3 copiada al portapapeles."
echo ""
whoami

