#!/bin/bash

# Verifica si se proporcionó un argumento (nombre del binario)
if [ $# -eq 0 ]; then
    echo "Uso: $0 <nombre_del_binario>"
    exit 1
fi

# Nombre del binario
binario=$1

# Ruta completa del binario en la máquina local
ruta_binario_local="/usr/bin/$binario"

# Verifica si el binario existe en /usr/bin en la máquina local
if [ ! -f "$ruta_binario_local" ]; then
    echo "El binario no se encontró en /usr/bin de la máquina local."
    exit 1
fi

# Pide al usuario la dirección de la máquina remota (formato usuario@ip)
echo "Introduce la dirección de la máquina remota (formato usuario@ip):"
read maquina_remota

# Pregunta si desea copiar el archivo a la máquina remota
echo "¿Deseas copiar el archivo a /tmp en la máquina remota? (s/n)"
read copiar_respuesta

if [[ $copiar_respuesta =~ ^[Ss]$ ]]; then
    # Transferir el binario a la máquina remota
    scp $ruta_binario_local $maquina_remota:/tmp/
    # Pregunta si desea ejecutar el archivo
    echo "¿Deseas ejecutar el archivo ahora en la máquina remota? (s/n)"
    read ejecutar_respuesta
    if [[ $ejecutar_respuesta =~ ^[Ss]$ ]]; then
        # Ejecutar el binario
        ssh $maquina_remota "chmod +x /tmp/$binario; /tmp/$binario"
    fi
else
    # Ejecutar el binario directamente en la máquina remota sin copiarlo
    cat $ruta_binario_local | ssh $maquina_remota "cat > /tmp/$binario; chmod +x /tmp/$binario; /tmp/$binario; rm /tmp/$binario"
fi
