#!/bin/bash

# Función para agregar configuración al archivo SSH
agregar_config_ssh() {
    local host_alias=$1
    local final_host=$2
    local jump_host=$3
    local ssh_config="$HOME/.ssh/config"

    # Crear el archivo config si no existe
    if [ ! -f "$ssh_config" ]; then
        touch "$ssh_config"
        chmod 600 "$ssh_config"
    fi

    # Descomponer la máquina final en usuario y host
    local final_user=$(echo $final_host | cut -d'@' -f1)
    local final_ip=$(echo $final_host | cut -d'@' -f2)

    # Añadir la nueva configuración al final del archivo config
    if [ -z "$jump_host" ]; then
        echo -e "\nHost $host_alias\n    HostName $final_ip\n    User $final_user" >> "$ssh_config"
    else
        echo -e "\nHost $host_alias\n    HostName $final_ip\n    User $final_user\n    ProxyJump $jump_host" >> "$ssh_config"
    fi

    cat "$HOME/.ssh/config"
    echo ""
    echo "La configuración ha sido añadida a ~/.ssh/config"
    echo ""
    echo "Para conectar solo ssh hostname"
    echo ""
}

# Menú principal
echo "Elige una opción:"
echo "1. Configurar conexión vía jump server"
echo "2. Configurar conexión directa a un servidor"
read -p "Selección: " opcion

case $opcion in
    1)
        read -p "Ingresa el alias para la máquina final: " final_alias
        read -p "Ingresa la máquina final en formato usuario@ip: " final_host
        read -p "Ingresa el jump host en formato usuario@ip: " jump_host
        agregar_config_ssh "$final_alias" "$final_host" "$jump_host"
        ;;
    2)
        read -p "Ingresa el alias para la máquina: " final_alias
        read -p "Ingresa la máquina final en formato usuario@ip: " final_host
        agregar_config_ssh "$final_alias" "$final_host"
        ;;
    *)
        echo "Opción no válida."
        ;;
esac
