#!/bin/zsh

# Crear un archivo temporal
tempfile=$(mktemp)

# Ejecutar el comando y almacenar la salida en el archivo temporal
ssa1 > "$tempfile"

# Puedes realizar otras operaciones con el archivo si es necesario
# Por ejemplo, mostrar su contenido con cat
bat -l rb "$tempfile"


# Verifica el estado del servicio SSH
systemctl is-active sshd &> /dev/null; 
echo "El servicio SSH está          **^^   ACTIVO   ^^**."
echo ""
