#!/bin/bash

# Check if an argument is given
if [ $# -eq 0 ]; then
    echo "Usage: ./script.sh [IP]"
    exit 1
fi

IP=$1

# Validate IP address format
if ! [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Invalid IP format. Please provide a valid IP address."
    exit 1
fi

# Check if the IP exists in banlist.txt and comment it out
if grep -q $IP "/var/artillery/banlist.txt"; then
    sudo sed -i "/$IP/ s/^/#/" "/var/artillery/banlist.txt"
    echo "IP $IP found and commented out in banlist."
else
    echo "IP $IP not found in banlist."
fi

