#!/bin/bash

# Pedir al usuario el nombre de la red (SSID) y la contraseña
read -p "Ingrese el nombre de la red (SSID): " ssid
read -sp "Ingrese la contraseña de la red: " password
echo

# Generar UUID para la conexión
uuid=$(uuidgen)

# Crear el archivo de configuración
config_file="${ssid}.nmconnection"

echo "[connection]
id=$ssid
uuid=$uuid
type=wifi
interface-name=wlan0
permissions=user:kali:;

[wifi]
mode=infrastructure
ssid=$ssid

[wifi-security]
auth-alg=open
key-mgmt=wpa-psk
psk=$password

[ipv4]
method=auto

[ipv6]
addr-gen-mode=default
method=auto

[proxy]" > $config_file

echo "Archivo de configuración generado: $config_file"

# Preguntar al usuario si desea ver el archivo
read -p "¿Desea ver el archivo? [S/n]: " ver_archivo
ver_archivo=${ver_archivo:-S} # Default a S si se presiona Enter

if [[ $ver_archivo =~ ^[Ss]$ ]]; then
    less $config_file
fi

# Preguntar si desea mover el archivo
read -p "¿Desea mover el archivo a /etc/NetworkManager/system-connections? [S/n]: " mover_archivo
mover_archivo=${mover_archivo:-S} # Default a S si se presiona Enter

if [[ $mover_archivo =~ ^[Ss]$ ]]; then
    sudo mv $config_file /etc/NetworkManager/system-connections/
fi

echo "cd /etc/NetworkManager/system-connections/"
