#!/bin/bash

# Preguntar por el nombre de la red
read -p "Nombre de la red: " network_name

# Preguntar por la contraseña de la red
read -s -p "Contraseña de la red: " network_password
echo  # Agregar una línea en blanco después de la entrada de contraseña

# Eliminar las líneas de configuración existentes de wlan0
sudo sed -i '/iface wlan0/,/^$/d' /etc/network/interfaces

# Agregar las nuevas líneas de configuración
echo "auto wlan0" | sudo tee -a /etc/network/interfaces
echo "iface wlan0 inet dhcp" | sudo tee -a /etc/network/interfaces
echo "    wpa-ssid \"$network_name\"" | sudo tee -a /etc/network/interfaces
echo "    wpa-psk \"$network_password\"" | sudo tee -a /etc/network/interfaces

# Reiniciar la red
sudo systemctl restart networking

echo "La configuración de red se ha actualizado y la red se ha reiniciado."
