#!/bin/bash

sudo systemctl set-default multi-user.target
sudo apt install kitty neofetch lsd wget git curl nmap        

rm -rf Music Pictures Public Templates Videos
echo ""
echo "Instalar manualmente tailscale con el siguiente comando"
echo ""
echo "curl -fsSL https://tailscale.com/install.sh | sh"
