#!/bin/zsh


#paso 2 instalar herramientas, crear alias, y mover binarios

sudo apt install lsd
sudo apt install net-tools
sudo apt install wormhole
sudo apt install ranger
sudo apt install scrub
sudo apt install shred

# Clonar fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

# Agregar alias a .zshrc
echo "alias smbserver='impacket-smbserver smbFolder \$(pwd) -smb2support -username 4rji -password 4rji123'" >> ~/.zshrc
echo "alias rmk='() { scrub -p dod \$1; shred -zun 10 -v \$1; }'" >> ~/.zshrc
echo "alias inst='sudo apt install'" >> ~/.zshrc
echo "alias bas='nano ~/.zshrc'" >> ~/.zshrc
echo "alias basrc='source ~/.zshrc'" >> ~/.zshrc
echo "alias mkt='mkdir content exploits nmap'" >> ~/.zshrc
echo "alias folder='cd /home/natasha/MaquinasHTB/nmap'" >> ~/.zshrc
echo "alias apu='sudo apt update && sudo apt upgrade'" >> ~/.zshrc
echo "alias pg='ping 8.8.8.8 -c2'" >> ~/.zshrc
echo "alias kittyconf='nano ~/.config/kitty/kitty.conf'" >> ~/.zshrc

## de el archivo primera
echo "alias cx='chmod +x '" >> ~/.bashrc
echo "alias f2r='sudo systemctl restart fail2ban'" >> ~/.bashrc
echo "alias f2s='sudo systemctl status fail2ban'" >> ~/.bashrc

rm -r Public Videos Music Pictures Templates Public Documents
