#!/bin/zsh

# Busca el archivo README.md
if [ -f "README.md" ]; then
    # Crea un archivo "dosl" con el contenido de la segunda columna separada por "=" en README.md
    awk -F= '{print $2}' README.md > dosl

    # Crea un archivo "unol" con el contenido de la primera columna en README.md
    awk '{print $1}' README.md > unol

    echo "Archivos dosl y unol creados exitosamente."
else
    echo "El archivo README.md no se ha encontrado en la ruta especificada."
fi

